DROP TABLE IF EXISTS
    users,
    companies,
    orders,
    order_items,
    factories,
    user_companies,
    item_prices,
    costumers,
    contacts,
    catalogs,
    items,
    available_factories_by_company,
    available_catalogs_by_company,
    schema_migrations;
